#ifndef CXA_CONFIG_H_
#define CXA_CONFIG_H_

#define CXA_FILE_DISABLE

#define CXA_ASSERT_LINE_NUM_ENABLE
#define CXA_ASSERT_GPIO_FLASH_ENABLE

#define CXA_LOGGER_BUFFERLEN_BYTES				80

//#define CXA_STATE_MACHINE_ENABLE_LOGGING

#endif
